spring:
  application:
    name: task-management
  datasource:
    url: jdbc:h2:file:./data/task_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true