spring:
  application:
    name: task-management
  datasource:
    url: jdbc:h2:file:./data/task_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true